### ISSUE TITLE
VIPER

### ISSUE THREAD

**Issue by ArtemKupriyanov** [JerryCh0/RayApplication#1]
Do U use VIPER Architecture in this case?

**Comment by ArtemKupriyanov** [comment]
https://github.com/JerryCh0/RayApplication/blob/daad497744dcca2a525b0bbc0ba60658a56543b0/Ray/Network/NetworkFacade.swift#L34
this is string so funny

**Comment by klabertants** [comment]
> Do U use VIPER Architecture in this case?

Yesn't
